#!/bin/bash

usage() {
	echo "Usage:"
    echo "Required: Enter .log file as first argument"
    echo "Optional: Enter .do file destination as second argument"
}

if [[ $# -eq 0 ]]; then
    usage
	exit 1
fi

if [ $1 == help ]; then
    usage
    exit 1
fi

log_file=$1
do_file=$2
log_ext="${log_file##*.}"

if [ $# -eq 2 ]; then
    dest=$do_file
else
    dest="${log_file%.*}.do"
fi

test -e $dest
if [ $? -eq 0 ]; then
    echo "$dest exists and will be overwritten."
    while true; do
        read -p "Continue? [y/N]: " yn
        case $yn in
            [Yy]* ) break;;
            * ) echo "Exiting..."; exit 0;;
        esac
    done
fi

if [ $log_ext == "log" ]; then
    grep -hE "^[>.] " $log_file | sed ':a;N;$!ba;s/\n> //g' | sed 's/^[.] //g '> $dest
    tail -n 1 $dest | grep "log close" >> /dev/null
    if [ $? -eq 0 ]; then
        head -n -1 $dest >> $dest
    fi
else
    echo "Only accepts unformatted .log files"
    exit 1
fi

exit 0
