#!/bin/bash

usage() {
	echo "Usage:"
    echo "Required: Enter .log file as first argument"
    echo "Optional: Enter .do file destination as second argument"
}

if [[ $# -eq 0 ]]; then
    usage
	exit 1
fi

if [ $1 == help ]; then
    usage
    exit 1
fi

log_file=$1
do_file=$2
log_ext="${log_file##*.}"

if [ $# -eq 2 ]; then
    dest=$do_file
else
    dest="${log_file%.*}.do"
fi

if [ $log_ext == "log" ]; then
    grep -hE "^[>.] " $log_file | sed ':a;N;$!ba;s/\n> //g' | sed 's/^[.] //g '> $dest
else
    echo "Only accepts unformatted .log files"
    exit 1
fi

exit 0
